name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.5
  http: ^1.2.2
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: NanumSquare
      fonts:
        - asset: assets/fonts/NanumSquare_acR.ttf
          weight: 400
        - asset: assets/fonts/NanumSquare_acB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquare_acEB.ttf
          weight: 800
